use_frameworks!

target 'DKFavoriteButton_Example' do
  pod 'DKFavoriteButton', :path => '../'

  target 'DKFavoriteButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
